# Generated by Django 4.2 on 2026-04-08 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('EEA', 'European Environment Agency'), ('COPERNICUS', 'Copernicus CAMS'), ('OPENAQ', 'OpenAQ'), ('OTHER', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(choices=[('PM25', 'PM₂.₅'), ('PM10', 'PM₁₀'), ('NO2', 'NO₂'), ('O3', 'O₃'), ('SO2', 'SO₂'), ('CO', 'CO')], max_length=10, unique=True)),
                ('description', models.TextField()),
                ('limit_oms', models.FloatField(help_text='Limite OMS en μg/m³')),
                ('limit_eu', models.FloatField(blank=True, help_text='Limite UE en μg/m³', null=True)),
                ('unit', models.CharField(default='μg/m³', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pollutants',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField(default=0, help_text='Altitude en mètres')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='airquality.city')),
            ],
            options={
                'verbose_name': 'Measurement Station',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('annual_deaths_europe', models.IntegerField(default=0, help_text='Décès estimés annuels en Europe')),
                ('vulnerable_groups', models.TextField(help_text='Groupes vulnérables, séparés par des virgules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_impacts', to='airquality.pollutant')),
            ],
            options={
                'verbose_name_plural': 'Health Impacts',
                'ordering': ['pollutant'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='airquality.country'),
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='μg/m³', max_length=20)),
                ('measurement_date', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='airquality.pollutant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='airquality.measurementstation')),
            ],
            options={
                'verbose_name_plural': 'Air Quality Data',
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='airqualitydata',
            index=models.Index(fields=['station', 'measurement_date'], name='airquality__station_e7ad60_idx'),
        ),
        migrations.AddIndex(
            model_name='airqualitydata',
            index=models.Index(fields=['pollutant', 'measurement_date'], name='airquality__polluta_01d3d5_idx'),
        ),
    ]
